### ISSUE TITLE
Restructuring repository

### ISSUE THREAD

**Issue by rafidini** [mgpai22/ergpy#1]
Hi, I was looking for repositories I could contribute to so I discovered this one here.

I am creating this issue in order to restructure it a bit the repo and you will tell me what you think about it.

**Comment by mgpai22** [comment]
I am open to it!

**Comment by rafidini** [comment]
> I am open to it!

If you could open a branch named `dev` for example and give me some right please for further developments.

**Comment by mgpai22** [comment]
Created "dev-branch". Do you have access to it?

**Comment by rafidini** [comment]
> Created "dev-branch". Do you have access to it?

Yes, you can check the PR now and test it. Thanks!

**Comment by mgpai22** [comment]
I quickly skimmed through the changes. They look wonderful, thank you!

PR has been merged into dev-branch. I will further test when I get the opportunity.

**Comment by mgpai22** [comment]
```
ERROR: No matching distribution found for stubgenj>=0.2.5
ERROR: No matching distribution found for JPype1>=1.3.0
```
I get these errors while installing with pip. Any idea how to amend them? I tried removing the strict requirements but it does not help.

**Comment by rafidini** [comment]
Here try this PR #3 of mine, I put instructions inside it. Check it out!

**Comment by mgpai22** [comment]
The Makefile does not give any issue. However is it possible to amend this issue when installing with pip?

I pushed the dev-branch on [TestPyPi](https://test.pypi.org/project/ergpy/).

`pip install -i https://test.pypi.org/simple/ ergpy`

Could the problem be that its on TestPyPi hence it can't find the proper stubgenj and JPype1 repo?

**Comment by rafidini** [comment]
> The Makefile does not give any issue. However is it possible to amend this issue when installing with pip?
> 
> 
> 
> I pushed the dev-branch on [TestPyPi](https://test.pypi.org/project/ergpy/).
> 
> 
> 
> `pip install -i https://test.pypi.org/simple/ ergpy`
> 
> 
> 
> Could the problem be that its on TestPyPi hence it can't find the proper stubgenj and JPype1 repo?

Ok, I will check that out

**Comment by rafidini** [comment]
I may have found the reason why it does not work on *TestPyPi* by looking at the Python doc.

> Note: This example uses --index-url flag to specify TestPyPI instead of live PyPI. Additionally, it specifies --no-deps. **Since TestPyPI doesn’t have the same packages as the live PyPI, it’s possible that attempting to install dependencies may fail or install something unexpected. While our example package doesn’t have any dependencies, it’s a good practice to avoid installing dependencies when using TestPyPI.**

- Source: https://packaging.python.org/en/latest/tutorials/packaging-projects/

So the required packages have to be installed by hand in addition to installing `ergpy` from **TestPyPi**

**Comment by mgpai22** [comment]
Perfect! Thank you.

**Comment by rafidini** [comment]
> Perfect! Thank you.

Tell me how it goes for the test.
