### ISSUE TITLE
No more than 16384 headers can be requested

### ISSUE THREAD

**Issue by rafidini** [mgpai22/ergpy#21]
Hello @mgpai22, let us go back on track 🚀

I committed some changes to the logs issue (#11), for now, it is very simple and I only added it to a new example (example_7_*.py) to make sure the feature works properly.

But I have an issue running the example, this is my output:

![Screenshot 2022-09-18 at 13 22 40](https://user-images.githubusercontent.com/65868019/190899599-68ba92e8-4998-438a-ae43-15bc23b39bca.png)

I'll create a new issue to separate it from this feature 🔧

_Originally posted by @rafidini in https://github.com/mgpai22/ergpy/issues/11#issuecomment-1250249078_

**Comment by rafidini** [comment]
The error:
```json
{
  "error" : 400,
  "reason" : "bad.request",
  "detail" : "No more than 16384 headers can be requested"
}
```

**Comment by mgpai22** [comment]
Hey, glad to get back to this!

I cannot seem to recreate it from my end...I don't see any errors.

So the official testnet has been faces issues for a new weeks. Lets create the ergo object as such:
```
NODE_URL: str = "https://pai-net.mempoolnode.live"  # MainNet or TestNet
API_URL: str = "https://api.mempoolnode.live"
ergo = appkit.ErgoAppKit(node_url=NODE_URL, api_url=API_URL)
```
Run this and let me know how it goes.

**Comment by rafidini** [comment]
Seems like it works with it.
