### ISSUE TITLE
PEP 8 – Style for Python Code

### ISSUE THREAD

**Issue by rafidini** [mgpai22/ergpy#4]
**Is your feature request related to a problem? Please describe.**
As this project is meant to become a **Python package**, it is highly recommended to make it follow the _**PEP 8 - Style Guide for Python Code**_.

Source : [PEP 8 – Style Guide for Python Code](https://peps.python.org/pep-0008/)

**Describe the solution you'd like**
Make all source code more **PEP 8**-friendly.

**Additional context**
> A python-jvm wrapper for interacting with the Ergo blockchain.

So we have to be careful of not following **Java** standards (at least try not to).

**Comment by rafidini** [comment]
@mgpai22, you just need to run some tests before merging into `main`.
Keep me updated on required changes.

**Comment by mgpai22** [comment]
Sounds good! I will probably conclude testing this weekend.

**Comment by rafidini** [comment]
> Sounds good! I will probably conclude testing this weekend.

Nice!

**Comment by mgpai22** [comment]
> @mgpai22, you just need to run some tests before merging into `main`. Keep me updated on required changes.

Hey sorry for the delay I got caught up with work.

So I began testing today. In the `example_1.py` file, when I call any function to print, I keep getting `None` printed to console. I have no idea why. In the functions itself in the `helper_function.py` I made it print to console rather than return and everything does work as expected.

**Comment by rafidini** [comment]
No problem @mgpai22, thanks for the feedback. I will try to check that out 👍

**Comment by mgpai22** [comment]
I tested everything with various scenarios and they work well! 

I am thinking of adding some sort of optional parameter to the ergo connection object to enable or disable logging. What do you think @rafidini ?

**Comment by rafidini** [comment]
> 

Well yeah, that would be useful for debugging purposes!  You can create an issue to describe the feature maybe
