### ISSUE TITLE
More admin rights

### ISSUE THREAD

**Issue by rafidini** [mgpai22/ergpy#7]
Hi, can you please give me more admin rights to make this repo alive? I would like to add many things such as : 
- **Actions** to automate tests
- **Discussions** to create polls and decide on the direction of this repo
- ... (still thinking of the rest)

You can also consider transforming your account into an organization.

**Comment by mgpai22** [comment]
I invited you to join as a collaborator. Does that help?

**Comment by rafidini** [comment]
Yes, it is good!

Can you enable _**Discussions**_ too? It is under the repository _Settings/General/Features_.

**UI**
Here is what you should find.

<img width="825" alt="Screenshot 2022-05-29 at 18 35 55" src="https://user-images.githubusercontent.com/65868019/170881143-da3fa5bd-4078-44a3-b155-45b42a1b9a5e.png">

**Comment by mgpai22** [comment]
Done!
