### ISSUE TITLE
Console does not exit

### ISSUE THREAD

**Issue by mgpai22** [mgpai22/ergpy#9]
Whenever the code is run I notice that something does not properly exit.

Try this code out:
```
from ergpy import helper_functions, appkit

node_url: str = "http://213.239.193.208:9052/"  # MainNet or TestNet
ergo = appkit.ErgoAppKit(node_url=node_url)
wallet_mnemonic = "what stadium typical spell rate truly pen tongue fuel intact fluid strike vibrant city shine"
receiver_addresses = [
    "3WwdXmYP39DLmDWJ6grH9ArXbWuCt2uGAh46VTfeGPrHKJJY6cSJ",
    "3WwuG9amNVDwkJdgT5Ce7aJCfeoafVmd9tag9AEiAZwgPi7pYX3w",
    "3Wxk5oofZ3Laq2CpFW4Fi9YQiaep9bZr6QFg4s4xpzz4bi9tZq2U"
]

amount = [0.22, 0.33, 0.11]

tx = helper_functions.simple_send(ergo=ergo, amount=amount, wallet_mnemonic=wallet_mnemonic, receiver_addresses=receiver_addresses)

data = f'Transaction: {str(tx)}'
with open('demo.text', 'w') as file:
    file.write(data)
print("wrote to file")

```
This will write the txid to file and print to console. However if you want to exit to run other commands in the console you must exit with `ctrl + c`.  I tried including `sys.exit(0)` and `quit()` in the code but it does not help.

Any ideas @rafidini ?

Thank you

**Comment by rafidini** [comment]
I will take a look

**Comment by mgpai22** [comment]
> By the way, I get the following exception, lack of funds maybe? Can you check this out @mgpai22?

Yeah so if you make transactions consequently it does that as they need to be confirmed. This can be achieved by waiting five minutes and running it again.

However a better way to test would be with this piece of code instead. 

```
tx = helper_functions.simple_send(ergo=ergo, amount=amount, wallet_mnemonic=wallet_mnemonic, receiver_addresses=receiver_addresses, base64reduced=True)

```
Instead of submitting the transaction, it just gives a base64 version of it. However this still does not exit the console. So it should be useful for debugging.

**Comment by rafidini** [comment]
**Update**
I found a solution after many tests, I will implement it in some way.

**Comment by rafidini** [comment]
I created the function you mentioned above but without the wrapper.
The function is called at the end of each example.
